version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    ports:
      - '8080:8080'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
