mutation Login($loginInput: LoginInput!) {
	login(loginInput: $loginInput) {
		accessToken
		refreshToken
		user {
			id
			email
			isAdmin
		}
	}
}

mutation Register($authInput: AuthInput!) {
	register(authInput: $authInput) {
		accessToken
		refreshToken
		user {
			id
			isAdmin
		}
	}
}

mutation GetNewTokens {
	newToken {
		refreshToken
		accessToken
	}
}
