mutation Login($loginInput: LoginInput!) {
	login(loginInput: $loginInput) {
		user {
			id
			email
			isAdmin
		}
	}
}

mutation Register($authInput: AuthInput!) {
	register(authInput: $authInput) {
		user {
			id
			email
			isAdmin
		}
	}
}

mutation Logout {
	logout
}

mutation GetNewTokens {
	newToken
}
