query GetAllProductsDashboard($getAllProductInput: GetAllProductInput!) {
	getAllProducts(getAllProductInput: $getAllProductInput) {
		length
		products {
			id
			images
			name
			price
			slug
			productColorId
			size {
				id
				name
			}
			colors {
				id
				imageCss
				name
			}
		}
	}
}

query GetProductByColor($getProductByColor: GetProductByColor!) {
	getProductByColor(getProductByColor: $getProductByColor) {
		id
		colors {
			id
			imageCss
			name
		}
		images
		name
		price
		productColorId
		description
		categoryId
		slug
		size {
			id
			name
		}
	}
}
