mutation ToggleFavoritesProfile($productId: Float!) {
	toggleFavoritesProfile(productId: $productId)
}

query GetUserFavoritesIdArray {
	getProfile {
		favorites {
			id
		}
	}
}

query GetUserFavoritesIdArray {
	getProfile {
		favorites {
			id
		}
	}
}

query GetAllFavorites {
	getProfile {
		favorites {
			id
			images
			name
			price
			productColorId
			slug
		}
	}
}
