import Provider from '@/Providers/Provider'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body>
				<Provider>
					<div className='wrapper'>
						<main>{children}</main>
					</div>
				</Provider>
			</body>
		</html>
	)
}
