name: deploy_prod

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x.x
      - run: npm i
      - run: npm run lint
      - run: npm run lint:types
      - run: npm run build
